### ISSUE TITLE
sanitize s3 bucket broken

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#188]
https://github.com/klothoplatform/klotho/actions/runs/4081876968/jobs/7035703875 has a failure for the bucket name saying its invalid. Removing now for other reasons as well which will be commented in code

**Comment by jhsinger-klotho** [comment]
Heres the error from the integ test

    aws:s3:Bucket ():
      error: 1 error occurred:
      	* Error creating S3 bucket: InvalidBucketName: The specified bucket is not valid.
      	status code: 400, request id: CTQ279AKVHPQCXDK, host id: QToJlyi21j4Q6sXlWr+hgiwf/PnU/jV3J/pB+/tAVuWtHndkt2GaV4CRDbs6rOy0yyHQyKHHMJc=
  
    pulumi:pulumi:Stack (ts-orm-environment-variable-directive-f-4081876968-ts-orm-environment-variable-directive-f-4081876968):
      error: update failed

**Comment by DavidSeptimus-Klotho** [comment]
The current bucket creation logic with sanitization enabled would output the following valid (truncated) bucket name:

`123456789012-ts-orm-environment-variable-directive-f-40`

That said, this definitely doesn't seem appropriate given we now support multiple buckets per app.
