### ISSUE TITLE
refactor fs to create buckets based on ID

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#227]
This setting is being used within the go implementation so that we can generate new buckets based on each `openBucket` Call. 

We have a new Buckets list within our aws provider template that when added to will generate a new bucket and inject an environment variable to the exec unit so they know which bucket to use. 

This will require runtime changes in python and node to use the env var instead of the hardcoded bucket name

This has been an ask by a user who is developing a multi language application that wants to share resources and this work will need to be done to allow for that

**Comment by atorres-klo** [comment]
Doing this will make other languages be interoperable with Go buckets. Currently they are not.
