### ISSUE TITLE
Stop spamming people!

### ISSUE THREAD

**Issue by dlorch** [klothoplatform/klotho#257]
Please stop the spam!

![Screenshot from 2023-02-17 21-29-23](https://user-images.githubusercontent.com/43927/219786833-8b1abf0d-f77b-44aa-96b5-1deb4ea17c80.png)

**Comment by Lilja** [comment]
Same here, I would assume this is from scraped github data.

**Comment by dlorch** [comment]
Not great. I have reported to https://support.github.com/contact/report-abuse

**Comment by AlaShibanAtKlo** [comment]
Apologies for that @dlorch @Lilja , we wanted to reach out to folks that have experience with AWS. We'll revise how we go about this.
