### ISSUE TITLE
Have a max app name length and allowed characters check

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#31]
as we sanitize resource names for IaC it will be a lot simpler if we have restrictions on the appname since we are going to use it in every resource name

**Comment by yuval-klotho** [comment]
Do we need to push this all the way to the customer, or can we do some sort of early-stage transform on it internally?

**Comment by yuval-klotho** [comment]
Discussed in triage. We're going to do this as written: it's an easy impl, and it's always easier to relax constraints than add new ones (from a backwards compat perspective).
