### ISSUE TITLE
Invalid S3 Bucket Name Environment Variable

### ISSUE THREAD

**Issue by DavidSeptimus-Klotho** [klothoplatform/klotho#317]
When attempting to deploy an app containing a cloud file system, an invalid bucket name environment variable is generated when the Klotho resource's ID contains invalid environment variable name characters.

This results in a failed deployment with the following error:
```
Diagnostics:
  pulumi:pulumi:Stack (DavidSeptimus-Klotho/ts-app/ds-ts-app)
    error: update failed
 
  aws:lambda:Function (executor)
    error: 1 error occurred:
	* creating Lambda Function (ts-app-executor): ValidationException: 
	status code: 400, request id: 21d4e862-1327-448e-82ff-76b82c9a72a4
```

Here's the underlying error returned by AWS when manually creating the function via the AWS CLI:

```
An error occurred (ValidationException) when calling the CreateFunction operation: 1 validation error detected: Value at 'environment.variables' failed to satisfy constraint: Map keys must satisfy constraint: [Member must satisfy regular expression pattern: [a-zA-Z]([a-zA-Z0-9_])+]
```

**Example:**

Resource:
```typescript
/**
 * @klotho::persist {
 * id = "fs-cloud"
 * }
 */
import fs = require("fs/promises");
```

Invalid environment variable:
`fs-cloud_bucket_name`

**Comment by jhsinger-klotho** [comment]
well we need to sanitize the ids when creating environment variables it looks like, seems like we just need to create a New method for environment variables so that the name always goes through sanitization. I can cut a ticket

**Comment by DavidSeptimus-Klotho** [comment]
Same applies when we're injecting variable names based on resource IDs
