### ISSUE TITLE
serverSideEncryptionConfiguration being changed

### ISSUE THREAD

**Issue by AlaShibanAtKlo** [klothoplatform/klotho#322]
![image](https://user-images.githubusercontent.com/96867907/222927816-d39db678-240e-46d3-8549-ad894128d6c9.png)

Serversi de encryption for S3 seems to be re-configuring after re-compiling even though I didn't modify related objects in the code.

**Comment by jhsinger-klotho** [comment]
we likely need to apply the default aws:kms key, looks like it was something added to pulumi as non-default anymore. Going to just pick this up now
