### ISSUE TITLE
EKS prereq chart setup

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#420]
Dependent on the task for helm charts being deployable

Setup all prerequisite charts if required:

- [ ] VPC CNI Plugin -> Always
  - [ ] in progress
  - [ ] done
- [ ] ALB chart -> if exposed exec unit
  - [x] in progress
  - [ ] done
- [x] Metrics server -> Always
  - [x] in progress
  - [x] done
- [x] Cert Manager -> always 
  - [x] in progress
  - [x] done
- [ ] NVidia driver -> If instance type is GPU (Configurable if we arent owning the cluster)
  - [ ] in progress
  - [ ] done
- [ ] Cloud map chart -> If proxy (lower-pri; only needed for multi exec. possibly defer to a separate task for multi-exec. this also uses kustomize instead of helm, so it may be worth spinning off to its own)
  - [ ] in progress
  - [ ] done

Stretch Goals **[deferred]**:
- [ ] Include chart dependencies within our klotho generated Chart.yaml (as opposed to pulumi)
    - not needed for now; requires some work on our `dependsOn` handling to call `ready()` as appropriate
- [ ] Include a high level cluster config that determines if these can be installed (This will be important when imported clusters are being used because we could negatively effect their clusters by installing these no matter what).
    - not needed for now; will be needed for imports

Definition Of Done:
- Determinations are made on which charts need to be installed
- Proper IaC Is rendered for these charts

**Comment by yuval-klotho** [comment]
Looking at the legacy `add_on` dirs: do we need to handle fluentbit as part of this work?

**Comment by jhsinger-klotho** [comment]
theres a separate task for fluentbit, which im handling at the moment
