### ISSUE TITLE
 Use appname namespace for all resources

### ISSUE THREAD

**Issue by yuval-klotho** [klothoplatform/klotho#49]
There's a few that aren't properly namespace'd. Do a sweep through all of the resources, but some I know at time of writing:

- API Gateway
- Log groups

We should also consider having a santize method purely for the length of the resource to ensure we will be able to create it.

**Comment by DavidSeptimus-Klotho** [comment]
Renaming resources has been decoped for now to avoid breaking changes to existing stacks. #108 implements sanitization only.
