### ISSUE TITLE
Support module with multiple imports with different alias

### ISSUE THREAD

**Issue by gordon-klotho** [klothoplatform/klotho#567]
Currently, this test case in `imports_test` demonstrates how it doesn't work
```go
{
	name: "import module aliased twice",
	source: `
		import module1 as a
		import module1 as b
`,
	want: map[string]Import{
		"module1": {Name: "module1", Alias: "a"},
	},
},
```

This shows that `FindImports` ignores the alias `b`.

**Comment by yuval-klotho** [comment]
Motivating use case:

```python
# @klotho::persist {
#   id = "main-fs"
# }
import aiofiles as klothofs

# @klotho::persist {
#   id = "secrets"
#   secret = true
# }
import aiofiles as secrets
```

**Comment by yuval-klotho** [comment]
Pulling into prioritization to at least better understand it.

- The big open question is, are we able to create both a secret and non-secret fs in a single py file?
- If the fix is simple, do it. If it's multi-day, please raise that in sync.

**Comment by gordon-klotho** [comment]
I don't think this bug is due to the import detection, but it does occur:

```py
# @klotho::persist {
#   id = "hello"
#   secret = true
# }
import aiofiles as secrets

# @klotho::persist {
#   id = "hello"
# }
import klotho_runtime.fs_hello as cloudfs
```

So it's somewhere in the persist plugin or annotation detection.
