### ISSUE TITLE
[doc] typo of docker run option

### ISSUE THREAD

**Issue by Yuhta28** [klothoplatform/klotho#576]
I found that the Insufficient docker run command written in the below document page.
https://klo.dev/docs/tutorials/your_first_klotho_app/#setting-up-your-docker-environment

```terminal
docker pull klothoplatform/klotho:latest

  alias docker-klotho='docker run --platform linux/amd64 --rm -it -w /usr/src/project -v ${HOME}/.klotho:/root/.klotho -v $(pwd):/usr/src/project klothoplatform/klotho:latest klotho'
  alias docker-npm='docker run --platform linux/amd64 --rm -it -w /usr/src/project -v ${HOME}/.npm:/root/.npm -v $(pwd):/usr/src/project klothoplatform/klotho:latest npm'
```

I run this command and the error occurred
```terminal
docker: invalid reference format.
See 'docker run --help'.
```

It seems to me that the environment variable of ${PWD} is written incorrectly.

#### docker-klotho
-  alias docker-klotho='docker run --platform linux/amd64 --rm -it -w /usr/src/project -v ${HOME}/.klotho:/root/.klotho -v *$(pwd)*:/usr/src/project klothoplatform/klotho:latest klotho' #before
- alias docker-klotho='docker run --platform linux/amd64 --rm -it -w /usr/src/project -v ${HOME}/.klotho:/root/.klotho -v *${pwd}*:/usr/src/project klothoplatform/klotho:latest klotho' #after

#### docker-npm
-  alias docker-npm='docker run --platform linux/amd64 --rm -it -w /usr/src/project -v ${HOME}/.npm:/root/.npm -v *$(pwd)*:/usr/src/project klothoplatform/klotho:latest npm' #before
-  alias docker-npm='docker run --platform linux/amd64 --rm -it -w /usr/src/project -v ${HOME}/.npm:/root/.npm -v *${pwd}*:/usr/src/project klothoplatform/klotho:latest npm' #after

Please check whenever you have time.

**Comment by yuval-klotho** [comment]
`$(pwd)` isn't an env var, it's subshell substitution.

```
echo "${PWD}"  # (with curlies): the env var "PWD"
echo "$(pwd)"  # (with parens): run the `pwd` command, and use its stdout as the arg value
```

Note that the `pwd` command simply outputs `$PWD`.

**Comment by yuval-klotho** [comment]
Ah, yes, I think that's it.

```bash
~$ docker-klotho --version
Version: v0.6.4-linux-amd64(pro)

~$ mkdir 'test with spaces'

~$ cd 'test with spaces'

~/test with spaces$ docker-klotho --version
Unable to find image 'with:latest' locally
```

Quoting the command fixes it:

```bash
~/test with spaces$ alias docker-klotho='docker run --platform linux/amd64 --rm -it -w /usr/src/project -v ${HOME}/.klotho:/root/.klotho -v "$(pwd):/usr/src/project" klothoplatform/klotho:latest klotho'

~/test with spaces$ docker-klotho --version
Version: v0.6.4-linux-amd64(pro)
```

I'll put a fix in. Thanks for pointing this out!

**Comment by yuval-klotho** [comment]
The fix is deployed, and while I was there I did also change `$(pwd)` to `$PWD` (which I find a bit more readable). The aliases are now:

```bash
alias docker-klotho='docker run --platform linux/amd64 --rm -it -w /usr/src/project -v ~/.klotho:/root/.klotho -v "$PWD:/usr/src/project" klothoplatform/klotho:latest klotho'
alias docker-npm='docker run --platform linux/amd64 --rm -it -w /usr/src/project -v ~/.npm:/root/.npm -v "$PWD:/usr/src/project" klothoplatform/klotho:latest npm'
```

Please reopen this ticket if these still don't work for you. Thanks again!
