### ISSUE TITLE
Fs Resource Create and Edge Expansion

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#603]
This task is meant to satisfy the Fs construct's expansion.

To do so we will:

- Add Create Methods for Each Resource necessary
    - [x] S3Bucket
- Add Configure Method For Each Resource Necessary
    - [x] S3Bucket
- Add the expand method for an fs construct and our internal resource construct
- My initial thought is that this will connect an edge from the method to their corresponding lambda
- Add EdgeKB data
    - [x] LambdaFunction -> S3Bucket
    - [x] IamPolicy -> S3Bucket

DoD:

- All Methods above are written and have unit tests
- ts-cloudfs (or any cloudfs) sample app is able to pass tests [ts-cloudfs](https://github.com/klothoplatform/sample-apps/tree/main/ts-cloudfs)

**Comment by yuval-klotho** [comment]
Similarly, removing the S3BucketPolicy — we need that for static files (#607), but not for FS
