### ISSUE TITLE
camelCase and dash-case conversion errors in index.ts

### ISSUE THREAD

**Issue by yuval-klotho** [klothoplatform/klotho#641]
When I ran `ts-static-unit`, I noticed this in the resulting `index.ts`:

```
const s3BucketYstestNternalLothoAyloads = new aws.s3.Bucket(
        `ystest--nternal-lotho-ayloads`,
        {
```

It looks like some code responsible for converting to camel case is mistakenly removing the first letter of every word. The same thing happens to the dashed resource name.

Fixing this would be a breaking change, since it changes the logical IDs for the Pulumi resources.

**Comment by atorres-klo** [comment]
This might only be for S3

**Comment by gordon-klotho** [comment]
Ideally move to use a library for case conversion too
