### ISSUE TITLE
revisit StageName for Expose + Cloudfront

### ISSUE THREAD

**Issue by yuval-klotho** [klothoplatform/klotho#653]
Similar to https://github.com/klothoplatform/klotho/issues/652, we currently hard-code the stage name to `"stage"`, because edge expansion happens before node configure (and the stage name only gets set in configure).

**Comment by gordon-klotho** [comment]
Probably best to change the factory.ts to use the stage's name property in IaC (ts) instead of the resource property (go).

**Comment by yuval-klotho** [comment]
I could definitely be missing something, but I think this requires a just a tad more than I originally thought it might. From 4b833b7:

> Unfortunately, the deployment doesn't have a stage at `pulumi up` time, so the origin path becomes `"/UNSPECIFIED_STAGE"` (literally that text).
> 
> I think to fix this, we would need to either:
> 
> - set the [Deployment's stageName][1]; or
> - explicitly [create a State][2]
> 
> In either case, we would no longer be relying on the implicit stage creation-and-naming.
> 
> [1]: https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/deployment/#stagename_nodejs
> [2]: https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/stage/

Neither of those is hard, but I did want to pause and make sure they're the right path forward.

I think the current code does amount to explicitly _using_ the `stageName`, based on what's implicitly created — which is not great! So maybe explicitly setting the stageName is the way to go.

**Comment by gordon-klotho** [comment]
> explicitly [create a State](https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/stage/)

I thought we did explicitly create one. Or was that only in HTTP gateway?

**Comment by yuval-klotho** [comment]
🤦 You're right, we do.

**Comment by yuval-klotho** [comment]
I think I got it now. Pulumi's weird typing threw me off: they have a circular dependency between Deployment and Stage. I can see why they did it, but at 830am on a Monday it got me.

**Comment by yuval-klotho** [comment]
Cool, got it working.

Since this came from #647, which hasn't been approved/merged yet, I just threw it into that existing PR. I'll keep this open for now just in case we end up rolling that part out before merging.
