### ISSUE TITLE
Allow additional rules in resource templates

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#825]
We want all properties to represent IAC Dependencies so that when someone adds an env variable or something similar we know how to depend on the resource in index.ts or respective iac file.

This causes issues today because the rest api has a property for api stages to ensure a stage is created, however a stage actually depends on the rest api in deployment order.

Temporarily we moved stage generation to an edge template, but should have a proper solution in place for this

**Comment by atorres-klo** [comment]
We have a workaround, but this is the better long term approach

**Comment by jhsinger-klotho** [comment]
picking this up since this is also affecting eks clusters
