### ISSUE TITLE
How to avoid Login?

### ISSUE THREAD

**Issue by kontrafiktion** [klothoplatform/klotho#833]
It seems that I cannot try Klotho without creating a Login.
I do not want to do that. 

It seems like there should be a `--local` flag (https://github.com/klothoplatform/klotho/issues/164), but it does not seem to exist in my version installed via `brew`.

Do I have to build Klotho myself to be able to avoid the login?

**Comment by gordon-klotho** [comment]
Hey there, thanks for trying out Klotho! Assuming you initially followed the instructions at https://klo.dev/docs/download-klotho, this installs the 'pro' version of Klotho. To switch to the open source version (or download it initially), you can follow the docs at https://klo.dev/docs/klotho-pro#switching-between-the-two-versions. While this doesn't have the `brew` instructions, it should enable switching from the one installed by default.
