### ISSUE TITLE
Install Klotho with scoop package manager

### ISSUE THREAD

**Issue by pcgeek86** [klothoplatform/klotho#99]
I noticed that the README doesn't have any directions to install Klotho on Windows.
I also noticed that there is a Windows binary for Klotho, in the Releases section on GitHub.
Most developer tools on Windows are packaged up for distribution with the Scoop package manager.

Could you guys add a Scoop package manifest file, to install Klotho via Scoop CLI? 
It's basically like MacOS Homebrew, but for Windows.

https://github.com/ScoopInstaller/Scoop

**Comment by ashiban** [comment]
Hey @pcgeek86 - that's likely an oversight on our end, we'll likely remove the .exe's for now - while we made sure klotho compiles on Windows, it's not a well tested route and for the time being suggest folks use WSL2 and the linux binaries for maximum compatibility. We are planning on support vanilla Windows down the line, but it's not on the hi-pri list at the moment.
